package module.barter.model;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

/**
 * The plan generated by the Algorithm(s) for optimal bartering.
 */
public class BarterPlan {

    private List<PlannedRoute> routes = new ArrayList<>();
    private double profit;

    /**
     * Default constructor.
     */
    public BarterPlan() {

    }

    /**
     * Adds a route to the plan.
     *
     * @param route The route to add.
     */
    public void addRoute(PlannedRoute route) {
        this.routes.add(route);
    }

    /**
     * Adds profit to the plan.
     *
     * @param profit The amount of profit to add.
     */
    public void addProfit(double profit) {
        this.profit += profit;
    }

    /**
     * @return A list of all the planned routes in order.
     */
    public List<PlannedRoute> getRoutes() {
        return routes;
    }

    /**
     * @return The total calculated profit from completing the plan.
     */
    public double getProfit() {
        return profit;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Barter Plan").append("\n");
        int step = 1;

        for (PlannedRoute route :routes) {
            sb.append(step++).append(". ").append(route.getTitle()).append("\n");
        }



        DecimalFormat formatter = new DecimalFormat("#,###");

        sb.append("Calculated Profit: ").append(formatter.format(getProfit()));


        return sb.toString();
    }
}
